# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-06-04 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0024_auto_20180604_2203'),
        ('django_dropimages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropimagesgallery',
            name='owner',
        ),
        migrations.DeleteModel(
            name='DropimagesGallery',
        ),
    ]
